name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'
  - title: '🧰 Maintenance'
    labels:
      - 'CI'
      - 'maintenance'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🔧 Other Changes'
    labels:
      - '*'
include-pre-releases: false
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
no-changes-template: '- No changes in this release'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's New
  $CHANGES
  
  ## Contributors
  
  Thank you to our contributors for making this release possible:
  $CONTRIBUTORS