# Copyright [2025] [SkywardAI]
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#        http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


FROM nvcr.io/nvidia/pytorch:25.12-py3

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies including zsh
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        zsh \
        git \
        curl && \
    rm -rf /var/lib/apt/lists/*

# Install Oh My Zsh
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# Set Zsh as the default shell
RUN chsh -s $(which zsh)

# Set the working directory
WORKDIR /workspace

LABEL org.opencontainers.image.authors="SkywardAI Labs" \
  org.opencontainers.image.url=https://github.com/SkywardAI/bundoora \
  org.opencontainers.image.source=https://github.com/SkywardAI/bundoora/blob/main/Dockerfile.pytorch

# Set the default shell to Zsh
CMD ["zsh"]